"""add email verification fields and fix default role

Revision ID: beb9b6a63ffe
Revises: c2aa5440197d
Create Date: 2026-02-08 17:56:18.603122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb9b6a63ffe'
down_revision: Union[str, None] = 'c2aa5440197d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # is_verified: mevcut kullanicilar dogrulanmis sayilir (server_default=true)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires', sa.DateTime(timezone=True), nullable=True))

    # Mevcut kullanicilarin role degerini "admin" olarak koru (yeni kayitlar "user" olacak)
    # Mevcut kullanicilari dogrulanmis olarak isaretle
    op.execute("UPDATE users SET is_verified = true WHERE is_verified = false")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code_expires')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
